### ISSUE TITLE
Nifi: What to persist? And do we need to use minio for that?

### ISSUE THREAD

**Issue by karimacherradi** [hannemariavister/terraform-nomad-nifi#13]
## What is the issue?
Discuss the options for persitence of Nifi and if we need to persist through minio?
## Suggestion(s)/solution(s) [Optional]
The recommended repositories to persist for Nifi are: 
https://github.com/xemuliam/docker-nifi#volumes
NiFi-specific:
    /opt/nifi/logs
    /opt/nifi/flowfile_repository
    /opt/nifi/database_repository
    /opt/nifi/content_repository
    /opt/nifi/provenance_repository
User-specific:
    /opt/datafiles
    /opt/scriptfiles
    /opt/certfiles

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by hannemariavister** [comment]
Branch: https://github.com/hannemariavister/terraform-nomad-nifi/tree/issue_3_persistence_storage_nomad shows a suggestion for persistence storage on Nomad. But after some research, we found out that NiFi might use [NiFi registry](https://github.com/hannemariavister/terraform-nomad-nifiregistry) for storing templates, which means that persistence storage is not necessary in this case...

**Comment by hannemariavister** [comment]
Not relevant.
