### ISSUE TITLE
Improve health checks for nifi service

### ISSUE THREAD

**Issue by hannemariavister** [hannemariavister/terraform-nomad-nifi#17]
## Feature description
Improve heath checks in [nifi.hcl](https://github.com/hannemariavister/terraform-nomad-nifi/blob/master/conf/nomad/nifi.hcl).

Some links: 
https://github.com/apache/nifi/pull/3266#issuecomment-466779550
https://nifi.apache.org/docs/nifi-docs/rest-api/index.html --> `System diagnostics`

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by AditiSharma77** [comment]
**check on NiFi node health from an external system**
 https://nifi.apache.org/docs/nifi-docs/rest-api/index.html --> System diagnostics

http://localhost:8182/nifi-api/system-diagnostics

**Comment by AditiSharma77** [comment]
One endpoint that gives a lot of metrics about current load, etc would be the system diagnostics REST endpoint

**Comment by AditiSharma77** [comment]
https://www.tutorialspoint.com/apache_nifi/apache_nifi_monitoring.htm

**Comment by AditiSharma77** [comment]
I have added nifi-api service and nifi -live (nifi is available or not )in nifi.hcl file .

**Comment by AditiSharma77** [comment]
https://repo1.dsop.io/dsop/opensource/apache/nifi/-/blob/6bbf738806c2a888888570192cd7dc53a9831d83/1.6.0/Dockerfile  
 
this is a link , why i have used /opt/nifi/ in health check
