### ISSUE TITLE
Persistence storage on nomad 

### ISSUE THREAD

**Issue by hannemariavister** [hannemariavister/terraform-nomad-nifi#3]
## Feature description
Like the others `terraform-nomad_xxxx`-modules, we need to offer persistence storage. By creating the variable `use_host_volume`, we able to parameterize this feature. 

## Definition of done
When the variable `use_host_volume` working, and the data is available in the `persistence/nifi` folder (on nomad)

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by karimacherradi** [comment]
Recommended for Nifi persistence: https://github.com/xemuliam/docker-nifi#volumes

**Comment by hannemariavister** [comment]
Branch: https://github.com/hannemariavister/terraform-nomad-nifi/tree/issue_3_persistence_storage_nomad shows a suggestion for persistence storage. But after some research, we found out that NiFi might use [NiFi registry](https://github.com/hannemariavister/terraform-nomad-nifiregistry) for storing templates, which means that persistence storage is not necessary in this case...

**Comment by hannemariavister** [comment]
Not relevant.
