### ISSUE TITLE
Error in testing 

### ISSUE THREAD

**Issue by AditiSharma77** [hannemariavister/terraform-nomad-nifi#34]
## Current behaviour
Changed version from config.vm.box_version = ">= 0.9, < 0.10 , so getting error in consul_acl_enviroment while testing.
## Suggestion(s)/solution(s) [Optional]
I checked this CI/CD with config.vm.box_version = ">= 0.7, < 0.8"   still getting same error 
## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by hannemariavister** [comment]
I think the reason why the pipeline fails is because the image `apache/nifi_1.12.1` is so large and it takes lot of time to pull down from Docker Hub. It seems that GitHub cancel the pipeline after 20 minutes. I suggest we try to increase the pipeline time by using [timeout_minutes](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) in [on_pr_push_master.yml](https://github.com/hannemariavister/terraform-nomad-nifi/blob/master/.github/workflows/on_pr_push_master.yml#L142).

**Comment by AditiSharma77** [comment]
okei , let me  check

**Comment by AditiSharma77** [comment]
> I think the reason why the pipeline fails is because the image `apache/nifi_1.12.1` is so large and it takes lot of time to pull down from Docker Hub. It seems that GitHub cancel the pipeline after 20 minutes. I suggest we try to increase the pipeline time by using [timeout_minutes](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) in [on_pr_push_master.yml](https://github.com/hannemariavister/terraform-nomad-nifi/blob/master/.github/workflows/on_pr_push_master.yml#L142).

Nifi fails after 20 m , 
jobs.<job_id>.timeout-minutes
**The maximum number of minutes to let a job run before GitHub automatically cancels it. **Default: 360****

**Comment by hannemariavister** [comment]
> > I think the reason why the pipeline fails is because the image `apache/nifi_1.12.1` is so large and it takes lot of time to pull down from Docker Hub. It seems that GitHub cancel the pipeline after 20 minutes. I suggest we try to increase the pipeline time by using [timeout_minutes](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) in [on_pr_push_master.yml](https://github.com/hannemariavister/terraform-nomad-nifi/blob/master/.github/workflows/on_pr_push_master.yml#L142).
> 
> Nifi fails after 20 m ,
> jobs.<job_id>.timeout-minutes
> **The maximum number of minutes to let a job run before GitHub automatically cancels it. **Default: 360****

If the default value is 360 minutes, why does the workflow ends after 20 minutes?

**Comment by AditiSharma77** [comment]
I think the problem is in consul_acl_enabled. I am checking about this .
