### ISSUE TITLE
Create a working `nifi-registry.hcl` 

### ISSUE THREAD

**Issue by hannemariavister** [hannemariavister/terraform-nomad-nifi#4]
## Feature description
In structure `conf/nomad/`, create a working nifi-registry hcl.

## Definition of done
When you are able to run the `nifi-registry.hcl` in nomad with no errors.

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by karimacherradi** [comment]
Nifi-registry til git: https://community.cloudera.com/t5/Community-Articles/Storing-Apache-NiFi-Versioned-Flows-in-a-Git-Repository/ta-p/24871
Versjonsstyring med nifi-registry: https://bryanbende.com/development/2018/01/19/apache-nifi-how-do-i-deploy-my-flow

**Comment by karimacherradi** [comment]
After discussion, we have decided to create nifi registry as a terraform module.
This issue will be closed and the work will be done in https://github.com/hannemariavister/terraform-nomad-nifiregistry
