### ISSUE TITLE
Include `standalone`- example with nifi-registry

### ISSUE THREAD

**Issue by hannemariavister** [hannemariavister/terraform-nomad-nifi#5]
## Feature description
Include nifi-registry in the [standalone-example](https://github.com/hannemariavister/terraform-nomad-nifi/tree/issue_2_create-example/example/standalone).

## Definition of done
After running `terraform init` and `terraform apply`, there should exist three working nomad jobs in nomad (`minio`, `nifi` and `nifi-registry`). 

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

**Comment by karimacherradi** [comment]
@hannemariavister tror denne kan lukkes, er duplikat av #26

**Comment by AditiSharma77** [comment]
dupllikat #26
