### ISSUE TITLE
Secrets managed by vault and consul-template

### ISSUE THREAD

**Issue by hannemariavister** [hannemariavister/terraform-nomad-nifi#9]
## Feature description
1. Key-value pairs (minio access and secret keys) exist already exist in the vault as a secrets
2. Secrets rendered in nomad_job via consul-template

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by karimacherradi** [comment]
Not relevant
